export enum Routes {
  ARCHIVE = '/archive',
  AUTH = '/auth',
  CATALOG = '/catalog',
  INSTANT = '/instant',
  NOT_FOUND = '/not-found',
  PACK_CREATION = '/pack-creation',
  QUESTION_CREATION = '/question-creation',
  ROOT = '/',
  TRAINING = '/training',
  READY_PACK = '/training/readyPack',
  RANDOM_PACK = '/training/randomPack',
  RANDOM_QUESTION = '/training/randomQuestion',
  MY_CREATED_GAMES = '/created-games',
}
