export enum Routes {
  ARCHIVE = '/archive',
  AUTH = '/auth',
  CATALOG = '/catalog',
  INSTANT = '/instant',
  NOT_FOUND = '/not-found',
  PACK_LIST = '/pack',
  PACK_CREATION = '/pack-create',
  PACK_UPDATE = '/pack-update',
  QUESTION_CRUD = '/question-crud',
  QUESTION_CREATION = '/question-creation/:packId',
  ROOT = '/',
  TRAINING = '/training',
  READY_PACK = '/training/readyPack',
  RANDOM_PACK = '/training/randomPack',
  RANDOM_QUESTION = '/training/randomQuestion',
  MY_CREATED_GAMES = '/created-games',
  NOTIFICATIONS = '/notifications',
}
